### ISSUE TITLE
500 Internal Server Error from alerts_add

### ISSUE THREAD

**Issue by BigDaddyBastonkadonkz** [tedchou12/webull#261]
Getting a 500 Internal Server Error when invoking alerts_add with the following exception:

Exception: ('alerts_add failed', 500, 'Internal Server Error')

Anyone encounter this?

**Comment by BigDaddyBastonkadonkz** [comment]
Here's an example:

pr = [{'field': 'price', 'type': 'above', 'value': '57.00', 'remark': 'TEST21'}]
result = wb.alerts_add('VZ', frequency=1, interval=1, priceRules=pr)
print(result)

Traceback (most recent call last):
  File "/Users/piaconis/Documents/Development/StonkTrader/StonkScreener/testOptPull.py", line 84, in <module>
    result = wb.alerts_add('VZ', frequency=1, interval=1, priceRules=pr)
  File "/usr/local/lib/python3.9/site-packages/webull/webull.py", line 869, in alerts_add
    raise Exception('alerts_add failed', response.status_code, response.reason)
Exception: ('alerts_add failed', 500, 'Internal Server Error')

Oddly enough, it adds the alert, but it also throws that error.

**Comment by asam007s** [comment]
I face another issue with setting Alert to Stock script.
After setting Alert using Alerts_Add (...) API i am not able to get the Notification call back.
I verified that the Alert is set successfully! But my question is : How do I get the notification if the Alert condition is met ?
