### ISSUE TITLE
The hasMore check in webull.py on line 268 is limiting returned good stocks from AMEX

### ISSUE THREAD

**Issue by timwelch** [tedchou12/webull#66]
https://github.com/tedchou12/webull/blob/e83b9a1d7d729a0a3098480560d6eb682b96f0e4/webull/webull.py#L268

for instance...

```
>>> wb.get_quote('NNVC')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/webull/webull.py", line 445, in get_quote
    tId = str(self.get_ticker(stock))
  File "/usr/local/lib/python3.7/site-packages/webull/webull.py", line 269, in get_ticker
    raise ValueError('TickerId could not be found for stock {}'.format(stock))
  ValueError: TickerId could not be found for stock NNVC

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/webull/webull.py", line 447, in get_quote
    raise ValueError("Could not find ticker for stock {}".format(stock))
ValueError: Could not find ticker for stock NNVC

```

But, **NNVC** is an actual good stock with a valid ticker ID

```
curl -k 'https://infoapi.webull.com/api/search/tickers5?keys=NNVC&queryNumber=1'| jq -r
{
  "categoryId": 0,
  "categoryName": "综合",
  "hasMore": false,
  "list": [
    {
      "tickerId": 913303706,
      "exchangeId": 12,
      "type": 2,
      "secType": [
        61
      ],
      "regionId": 6,
      "regionCode": "US",
      "currencyId": 247,
      "name": "NANOVIRICIDES",
      "symbol": "NNVC",
      "disSymbol": "NNVC",
      "disExchangeCode": "AMEX",
      "exchangeCode": "ASE",
      "listStatus": 1,
      "template": "stock"
    }
  ]
}
```

**Comment by timwelch** [comment]
Not sure what else it could break ... but in my local copy, I changed webull.py from:
```

            if result['hasMore'] == False:
                raise ValueError('TickerId could not be found for stock {}'.format(stock))
            elif result['list']:

```

to this...

```
            # if result['hasMore'] == False:
            #    raise ValueError('TickerId could not be found for stock {}'.format(stock))
            if result['list']:
```

And now AMEX tickers like NNVC return for me.

**Comment by timwelch** [comment]
It looks like, if you give it an actual invalid ticker, it will ONLY return:

```
{
  "hasMore": false
}
```

So, I would actually suggest ditching the hasMore check like I did above, because if `result['list']` exists, then there should be a tickerId in there. Could also go one step further and add the check for tickerId in `result['list'][0]` as well...

**Comment by spencerrojahn** [comment]
I was getting the same hasMore error with qet_quote(). I tried to use this solution but the error was not resolved.

**Comment by timwelch** [comment]
Yeah, sometime last night or this morning, Webull actually changed the endpoint URL for these things.

I have downloaded the fixed code from this PR [(](https://github.com/tedchou12/webull/pull/63) and verified that it fixed the issue.

**Comment by timwelch** [comment]
Confirmed PR [63](https://github.com/tedchou12/webull/pull/63) fixed this.
